name: Melchior
slogan: Let me try!
description: MonoHue's Blog.
baseurl: "https://monohue.net"
githuburl: "https://github.com/Monohue"
websuffix: " - Melchior"

paginate: 10
paginate_path: "page:num"

lighttheme: "light"
darktheme: "dark"
excerpt_separator: "<!-- more -->"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed