name: Melchior
slogan: Exploring the very nature of science.
description: MonoHue's Blog.
baseurl: "https://monohue.net"
githuburl: "https://github.com/Monohue"
websuffix: " - Melchior"

paginate: 10
paginate_path: "page:num"

lighttheme: "light"
darktheme: "dark"
excerpt_separator: "<!-- more -->"
markdown: kramdown

sass:
  style: compressed